name: Server Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ./production.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wassali:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: copy docker-compose to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password : ${{ secrets.SERVER_USER_PASSWORD }}
        source: "docker-compose.production.yml"
        target: "/home/${{ secrets.SERVER_USERNAME }}/wassali/"


    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_USER_PASSWORD }}
        script: |
          cd ~/wassali && cp ~/env/.env* ./
          docker compose -f docker-compose.production.yml pull
          docker compose -f docker-compose.production.yml up -d --remove-orphans
          docker image prune -f